package tarc.edu.carpartsapp

import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.Toast
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.database.*
import com.google.firebase.database.ktx.database
import com.google.firebase.ktx.Firebase
import tarc.edu.carpartsapp.Adapter.CustomerViewDeliveryStatusAdapter
import tarc.edu.carpartsapp.Adapter.DeliveryNeededAdapter
import tarc.edu.carpartsapp.Adapter.DeliveryStatusProductsAdapter
import tarc.edu.carpartsapp.Adapter.DeliveryStatusProductsCreditCardAdapter
import tarc.edu.carpartsapp.Model.Deliveries
import tarc.edu.carpartsapp.Model.DeliveryStatus
import tarc.edu.carpartsapp.databinding.FragmentCustDeliveryStatusBinding
import tarc.edu.carpartsapp.databinding.FragmentCustDeliveryStatusCreditCardBinding
import tarc.edu.carpartsapp.databinding.FragmentViewAllDeliveryBinding
